### ISSUE TITLE
选择仓库时失败，求助

### ISSUE THREAD

**Issue by zxmav** [Wexagonal/Wexagonal#1]
大佬求助，在选择选择Hexo指定的仓库的这一步出现错误
![image](https://user-images.githubusercontent.com/56088580/160116976-73e050ef-0f53-4d90-80ad-a0b003a9275f.png)
![image](https://user-images.githubusercontent.com/56088580/160117025-a5db70ef-b661-4ac0-952a-bbfdb41578ef.png)

**Comment by zxmav** [comment]
尝试过选择其他仓库，页面能加载出来
![(A_~G7 T15GP%FQS8UORL_I](https://user-images.githubusercontent.com/56088580/160117170-eab4b166-6198-40ef-bfe3-27500007f175.jpg)

**Comment by zxmav** [comment]
不知道是不是mongodb的配置问题，但是myFirstDatabase我替换成了数据库的名字，<password> 也整个换成了密码，应该来说没问题的，用的是vercel配mongodb，vercel目前显示{"ok":1,"db":1,"install":0}

**Comment by zxmacc** [comment]
github的token，我把全部的方框给勾上了
（刚刚那个是小号，上错号了QwQ）

**Comment by zxmacc** [comment]
![8MXUI23P6DI$7$2C1G{OF5M](https://user-images.githubusercontent.com/71143103/160229019-3d21404c-4e00-4f61-86d2-9d3f8e864943.png)
目前是这样

**Comment by ChenYFan** [comment]
1. 请问当前部署的后端是多少?
2. 仓库能给我读取权限吗?
3. 如果有能力调试,不妨进入Vercel的Function页面监听日志并截图

**Comment by zxmav** [comment]
当前部署后端已更新到0.0.1-beta-12，部署后选择仓库还是出现以上Failed页面
后端仓库和源码仓库已给予读取权限，等待同意
仓库地址：
https://github.com/zxmacc/Wexagonal
https://github.com/zxmacc/Hexo-zxmacc
Vercel的Function页面目前一直加载不出日志，显示正在等待新请求...

**Comment by zxmav** [comment]
那个Wexagonal仓库里的Readme我给了后端地址和数据库链接OvO

**Comment by ChenYFan** [comment]
报错截图:

![image](https://user-images.githubusercontent.com/53730587/160238449-9805eeab-243a-4aa6-b338-b1148cebc6e7.png)
初步推断config.yml格式有问题

**Comment by zxmav** [comment]
好的，那我先删除这段试试

**Comment by ChenYFan** [comment]
![image](https://user-images.githubusercontent.com/53730587/160238503-017a7afb-ae37-41cc-b562-4979f1d70c0e.png)
应该是一个Tab,你这里是不是弄成空格了

**Comment by ChenYFan** [comment]
我这里已经正常了:
![image](https://user-images.githubusercontent.com/53730587/160238670-9773908d-d09c-4b6e-a9cc-48604aa84db3.png)
你可以移除我的读权限了

**Comment by zxmav** [comment]
![image](https://user-images.githubusercontent.com/56088580/160238655-faec547e-f82e-4fd6-ab87-2fd8dac41ce4.png)
![image](https://user-images.githubusercontent.com/56088580/160238665-b50a32f8-083b-4c3b-9c02-32e795dd7784.png)
感谢大佬，已经可以了
