### ISSUE TITLE
[help]全是绿的，但是检查失败

### ISSUE THREAD

**Issue by lbr77** [Wexagonal/Wexagonal#2]
![image](https://user-images.githubusercontent.com/53066066/160228693-4416b08d-d3e7-4759-a947-507ad854e40d.png)
🤔

**Comment by ChenYFan** [comment]
1. 主题配置文件无法获取
2. 请尝试更新后端到最新版本,beta-7之前的后端无法识别以npm安装的主题

**Comment by lbr77** [comment]
1.主题配置文件在根目录
![image](https://user-images.githubusercontent.com/53066066/160231049-142b03ee-a5ad-486b-9ac4-e98890031613.png)

2.版本如下
![image](https://user-images.githubusercontent.com/53066066/160231033-ecf3e90d-b8a8-4df9-9968-84a9192b7d63.png)

**Comment by ChenYFan** [comment]
请问_config.yml中的theme键是多少?

**Comment by ChenYFan** [comment]
ok我可能找到错误位置了`/utils/app/hexo.js` L111应该是hres而不是config

**Comment by ChenYFan** [comment]
已经推了beta-13,你试着更新一下

**Comment by lbr77** [comment]
可以了
