### ISSUE TITLE
在绑定hexo中的workflow时出错

### ISSUE THREAD

**Issue by GuaiJieYo** [Wexagonal/Wexagonal#3]
![image](https://user-images.githubusercontent.com/73426727/168463224-0920601f-2ce2-4eb4-ab9e-912cd56c47f9.png)
如上图 点击绑定workflow时就出现这种错误TypeError: Failed to fetch
是因为我workflow有误吗（如果是请将正确的workflow文件发出来）
希望作者大大能够解决

**Comment by ChenYFan** [comment]
应该是workflow中没有on或者on事件不是数组。。。这问题已经知道了。

**Comment by GuaiJieYo** [comment]
> 应该是workflow中没有on或者on事件不是数组。。。这问题已经知道了。

所以解决办法是什么呢

**Comment by ChenYFan** [comment]
> > 应该是workflow中没有on或者on事件不是数组。。。这问题已经知道了。
> 
> 所以解决办法是什么呢

改workflow，不过可能不方便，你也可以等下个版本
