### ISSUE TITLE
部署失败，报HTTP ERROR 500

### ISSUE THREAD

**Issue by NoctuG** [Wexagonal/Wexagonal#5]
安装平台：Vercel
数据库：mongodb
_____________________________

* 操作复现

- 在 <https://cloud.mongodb.com/> 创建数据库，登陆用户名和密码，对所有ip开放，获取连接地址串 `mongodb+srv://sdfty:<password>@cluster0.r98ku.mongodb.net/?retryWrites=true&w=majority`
- 在公共面板配置，按步骤输入 URI `mongodb+srv://sdfty<password>`
- 按提示配置环境变量 `{"type":"MONGODB","endpoint":"mongodb+srv://sdfty:<password>"}`
- 重新部署，打开部署页面 <https://admin-hexo-nine.vercel.app/> 报错（如下图所示）
![f5324cfcdeafbdb4bbed83c4e9aefc09.jpg](https://ttfou.com/images/2022/06/16/f5324cfcdeafbdb4bbed83c4e9aefc09.jpg)

**Comment by NoctuG** [comment]
检查后调整了URI的格式，现在页面报错 ` {"ok":1,"db":1,"install":0,"version":"0.0.1-beta-20"}`

**Comment by ChenYFan** [comment]
> 检查后调整了URI的格式，现在页面报错 ` {"ok":1,"db":1,"install":0,"version":"0.0.1-beta-20"}`

到这一步就是安装成功了,请前往主面板继续操作

**Comment by NoctuG** [comment]
> > 检查后调整了URI的格式，现在页面报错 ` {"ok":1,"db":1,"install":0,"version":"0.0.1-beta-20"}`
> 
> 到这一步就是安装成功了,请前往主面板继续操作

问题已解决，谢谢回复。
