### ISSUE TITLE
部署完成后，访问报错

### ISSUE THREAD

**Issue by dengchangdong** [Wexagonal/Wexagonal#7]
部署平台：Vercel
数据库：MongoDB
访问报错：{"ok":1,"db":1,"install":0,"version":"0.0.1-beta-20"}
请问该怎么解决，谢谢！

**Comment by ChenYFan** [comment]
这就是部署成功了啊。。。

**Comment by ChenYFan** [comment]
你应该去公共面板 https://dash.wexa.top
