### ISSUE TITLE
mongodb + vercel 每次在“选择Hexo源码的分支”这一步选择之后意外退出(TypeError: Failed to fetch)

### ISSUE THREAD

**Issue by Liynw** [Wexagonal/Wexagonal#8]
控制台报错如下：

![](https://camo.githubusercontent.com/f023b5aa6e3618a73ee4f2d436c807a22ed73d0c8f7d3ce1cfcddf984cbe6fdf/68747470733a2f2f7069632e696d6764622e636e2f6974656d2f3632656233363763313666326332626562313165333138622e6a7067)

**Comment by Liynw** [comment]
现在 vercel 的项目显示的是 `{"ok":1,"db":1,"install":0,"version":"0.0.1-beta-20"}`

另外，选此仓库的另一个分支不会意外退出，如图

![](https://camo.githubusercontent.com/ff76e89d12f7b4a54ee729f4df70c122f7985e1fac6ed22a2d25f3c8c625584b/68747470733a2f2f66696c65732e696d6764622e636e2f7374617469632f696d616765732f30312f38642f3632656361653064386336316463336238656430303138642e6a7067)

**Comment by Liynw** [comment]
vercel 的 function 报错如下，没看懂：

![](https://camo.githubusercontent.com/c1a55438b9d0f7159a08b15e21e996c86d32b478727f79f08ab8f1dea1f0f4e0/68747470733a2f2f7069632e726d622e62647374617469632e636f6d2f626a682f63343834663430356364316534643233383034323237353866346562653665322e706e67)

**Comment by ChenYFan** [comment]
图片看不到，麻烦直接粘贴用github camo

**Comment by Liynw** [comment]
> 图片看不到，麻烦直接粘贴用github camo

done.

**Comment by XINGMOUREN** [comment]
我也遇到过同样的问题，解决方法如下
1.hexo init 重新配置一个hexo博客
2.备份之前的代码
3.把新配置的hexo代码上传github仓库
4.进入后台绑定仓库（新上传hexo代码的仓库）
5.绑定成功后，再把之前的代码回档一下
6.清除缓存
ps：这个方法是在隔壁qexo发现的，我在这里也试过是ok的

**Comment by ChenYFan** [comment]
![image](https://user-images.githubusercontent.com/53730587/183386248-bc5296e9-aac3-4f5e-935d-b59519017ac7.png)

见鬼，我还是看不到图片。

此外，这个问题一般是配置文件或packagejson错误导致的，条件不足我也没法判断

**Comment by Liynw** [comment]
> 我也遇到过同样的问题，解决方法如下 1.hexo init 重新配置一个hexo博客 2.备份之前的代码 3.把新配置的hexo代码上传github仓库 4.进入后台绑定仓库（新上传hexo代码的仓库） 5.绑定成功后，再把之前的代码回档一下 6.清除缓存 ps：这个方法是在隔壁qexo发现的，我在这里也试过是ok的

还是不行

**Comment by ChenYFan** [comment]
> > 我也遇到过同样的问题，解决方法如下 1.hexo init 重新配置一个hexo博客 2.备份之前的代码 3.把新配置的hexo代码上传github仓库 4.进入后台绑定仓库（新上传hexo代码的仓库） 5.绑定成功后，再把之前的代码回档一下 6.清除缓存 ps：这个方法是在隔壁qexo发现的，我在这里也试过是ok的
> 
> 还是不行

初步排查是theme配置项或者theme配置文件丢失，具体的话我还要看一下仓库文件

**Comment by ChenYFan** [comment]
如果方便的话请给@ChenYFan https://github.com/cqbzljt/OIBlog-Code 仓库的Read权限，我会前来排查

**Comment by Liynw** [comment]
> 如果方便的话请给@ChenYFan https://github.com/cqbzljt/OIBlog-Code 仓库的Read权限，我会前来排查

done.

**Comment by Liynw** [comment]
现在好了……

应该是那个 `master` 分支本身的问题，但是我不知道是什么原理……

新建了一个分支上传就好了！
